### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by remaxz** [Shawminator/DayZeEditor#1]
Hi man.

Can u release that?
DarkUI and TreeView are missing, i added, but failed.

**Comment by Shawminator** [comment]
https://drive.google.com/drive/folders/1ttA1bLUM-8-UnadaJqyf7cix-nY7zNtz

they are libraries, everything you need should be availabe in the above link. needs to be in the same structure as the google drive.

if you need further help feel free to join my discord https://discord.gg/5EHE49Kjsv
