### ISSUE TITLE
After update - Case Type Changes on Jsons/xmls

### ISSUE THREAD

**Issue by rklxmok** [Shawminator/DayZeEditor#12]
As stated, if my xmls/jsons in my linux server are in ex: Ammo.json format
![image](https://github.com/user-attachments/assets/46a9ac48-cccb-464b-bb84-6767088d2555)

then when the project is imported into the Editor it pulls them in all caps, ex: AMMO.json 
![image](https://github.com/user-attachments/assets/c3b84412-e085-48ca-bf07-61239a5138f5)

If I edit the files and export them, the market tries to load them twice. So I am editing the file names and deleting the all caps entries with each edit. 

This only started occurring after the recent update. Any help would be appreciated

KB

**Comment by Shawminator** [comment]
Answered on doscord

**Comment by Shawminator** [comment]
Answered on doscotd
