### ISSUE TITLE
You have a trojan in your release

### ISSUE THREAD

**Issue by je-na** [Shawminator/DayZeEditor#6]
Trojan in the latest release on the github releases page..

![image](https://github.com/Shawminator/DayZeEditor/assets/127786520/c0233329-2ae1-4141-965c-4fc47d947915)

**Comment by Shawminator** [comment]
I Believe this is flagged as a false positive.
![Screenshot 2024-01-12 192021](https://github.com/Shawminator/DayZeEditor/assets/44495972/f7b75fc1-fa78-4d76-9805-f9f73d581d14)
Windows defender scan finds all clear.
virus total only picks up 1 from 69 vendors marks it as malicious.

the code is avavible here for you look at if you so wish

**Comment by je-na** [comment]
Nope, not at all false. 

I ran it thru veracode and sonaqube (enterprise code scanning tools, used in git pipelines, etc. 

Both flagged it for the same. 

Its definetely infected, or a reliant dependency is.
